//
//  TrainInterfaces.swift
//  Dart
//
//  Created by Tomislav Luketic on 28/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol TrainWireframeInterface: WireframeInterface {
}

protocol TrainViewInterface: ViewInterface {
  func addStationAnnotations(_ stations: [Station])
  func refreshMap()
}

protocol TrainPresenterInterface: PresenterInterface {
  var selectedTrain: ObjTrainPositions? { get }
  func getCurrentTrains()
  func release()
}

protocol TrainInteractorInterface: InteractorInterface {
  var onTimer: (() -> Void)? { get set }
  func getCurrentTrains(completion: @escaping TrainPositionsCompletionBlock)
}
