//
//  TrainWireframe.swift
//  Dart
//
//  Created by Tomislav Luketic on 28/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TrainWireframe: BaseWireframe {

  // MARK: - Private properties -

  private let storyboard = UIStoryboard(name: "Train", bundle: nil)

  // MARK: - Module setup -

  init(info: StationAndTrainInfo, client: RailClientType) {
    let moduleViewController = storyboard.instantiateViewController(ofType: TrainViewController.self)
    super.init(viewController: moduleViewController)
    
    let interactor = TrainInteractor(client: client)
    let presenter = TrainPresenter(view: moduleViewController,
                                   interactor: interactor,
                                   wireframe: self,
                                   info: info)
    moduleViewController.presenter = presenter
 }

}

// MARK: - Extensions -

extension TrainWireframe: TrainWireframeInterface {
}
