//
//  HomeInteractor.swift
//  Dart
//
//  Created by Tomislav Luketic on 27/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
}
