//
//  TrainsWireframe.swift
//  Dart
//
//  Created by Tomislav Luketic on 30/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TrainsWireframe: BaseWireframe {

  // MARK: - Private properties -

  private let storyboard = UIStoryboard(name: "Trains", bundle: nil)

  // MARK: - Module setup -

  init(client: RailClientType) {
      let moduleViewController = storyboard.instantiateViewController(ofType: TrainsViewController.self)
      super.init(viewController: moduleViewController)
      
      let interactor = TrainsInteractor(client: client)
      let presenter = TrainsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
      moduleViewController.presenter = presenter
  }

}

// MARK: - Extensions -

extension TrainsWireframe: TrainsWireframeInterface {
  func navigate(to option: TrainsNavigationOption) {
    switch option {
    case .trainMap(let info, let client):
      let train = TrainWireframe(info: info, client: client)
      self.navigationController?.pushWireframe(train)
    }
  }
}
