//
//  TrainsInteractor.swift
//  Dart
//
//  Created by Tomislav Luketic on 30/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TrainsInteractor {
  
  let client: RailClientType

  init(client: RailClientType) {
    self.client = client
  }
}

// MARK: - Extensions -

extension TrainsInteractor: TrainsInteractorInterface {
  func getCurrentTrains(completion: @escaping TrainPositionsCompletionBlock) {
    client.getCurrentTrains { result in
      completion(result)
    }
  }
  
  func getAllStations(type: String?, completion: @escaping StationCompletionBlock) {
    client.getAllStations(type: type) { result in
      completion(result)
    }
  }
}
