//
//  HomeInterfaces.swift
//  Dart
//
//  Created by Tomislav Luketic on 27/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationOption {
  case trainMap(info: StationAndTrainInfo, client: RailClientType)
}

protocol HomeWireframeInterface: WireframeInterface {
  func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
  func reloadStations()
  func reloadStationsData()
  func selectedStationChanged()
  func stationsDataChanged(containing directions: [String])
}

protocol HomePresenterInterface: PresenterInterface {
  var filteredStations: [ObjStation] { get }
  var filteredStationsData: [ObjStationData] { get }
  var selectedStation: ObjStation? { get }
  func filterStations(text: String?)
  func getAllStations(type: String?)
  func stationSelected(at row: Int)
  func trainSelected(at row: Int)
  func getStationData(by code: String)
  func directionChanged(index: Int)
}

protocol HomeInteractorInterface: InteractorInterface {
  var client: RailClientType { get }
  func getAllStations(type: String?, completion: @escaping StationCompletionBlock)
  func getStationData(by code: String, completion: @escaping StationDataCompletionBlock)
}
