//
//  HomeInteractor.swift
//  Dart
//
//  Created by Tomislav Luketic on 27/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
  
  let client: RailClientType

  init(client: RailClientType) {
    self.client = client
  }
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
  func getAllStations(type: String?, completion: @escaping StationCompletionBlock) {
    client.getAllStations(type: type) { result in
      completion(result)
    }
  }
  
  func getStationData(by code: String, completion: @escaping StationDataCompletionBlock) {
    client.getStationData(by: code) { result in
      completion(result)
    }
  }
}
