//
//  HomeWireframe.swift
//  Dart
//
//  Created by Tomislav Luketic on 27/06/2020.
//  Copyright (c) 2020 lux. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe {

  // MARK: - Private properties -

  private let storyboard = UIStoryboard(name: "Home", bundle: nil)
  
  // MARK: - Module setup -

  init(client: RailClientType) {
    
    let moduleViewController = storyboard.instantiateViewController(ofType: HomeViewController.self)
    super.init(viewController: moduleViewController)
    
    let interactor = HomeInteractor(client: client)
    let presenter = HomePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
    moduleViewController.presenter = presenter
  }
}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {
  func navigate(to option: HomeNavigationOption) {
    switch option {
    case .trainMap(let info, let client):
      let train = TrainWireframe(info: info, client: client)
      self.navigationController?.pushWireframe(train)
    }
  }
}

